package catalog

import (
	"fmt"
	"strconv"
	"strings"
)

// This file writes the published files. Nothing here decides anything: every
// number it prints came out of Build, so a page cannot disagree with the
// inventory it was generated from.

const generated = "# Generated by go-desktop/catalog from the live GitHub organisation list.\n" +
	"# Edit families.json for the prose; never edit a count here.\n"

// quoteTOML renders s as a TOML basic string.
func quoteTOML(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// HugoTOML renders the landing page's site configuration: one array-of-tables
// entry per family, each with its organisations.
func (c *Catalog) HugoTOML() []byte {
	var b strings.Builder
	b.WriteString(`baseURL = "https://go-desktop.github.io/"` + "\n")
	b.WriteString(`title = "go-desktop"` + "\n")
	b.WriteString(`disableKinds = ["taxonomy", "term", "RSS", "sitemap", "404"]` + "\n\n")
	b.WriteString("[markup.goldmark.renderer]\n  unsafe = true\n\n")
	b.WriteString(generated + "\n")
	for _, f := range c.Families {
		b.WriteString("[[params.families]]\n")
		fmt.Fprintf(&b, "  key = %s\n", quoteTOML(f.Key))
		fmt.Fprintf(&b, "  title = %s\n", quoteTOML(f.Title))
		fmt.Fprintf(&b, "  blurb = %s\n", quoteTOML(f.Blurb))
		for _, o := range f.Orgs {
			b.WriteString("  [[params.families.orgs]]\n")
			fmt.Fprintf(&b, "    name = %s\n", quoteTOML(o.Name))
			fmt.Fprintf(&b, "    repos = %d\n", o.Repos)
			fmt.Fprintf(&b, "    site = %t\n", o.Site)
			fmt.Fprintf(&b, "    docs = %t\n", o.Docs)
			fmt.Fprintf(&b, "    role = %s\n", quoteTOML(o.Role))
		}
		b.WriteString("\n")
	}
	return []byte(b.String())
}

// EcosystemTOML renders the landing page's data file: the gem organisations, the
// reserved names, and the gem repository total the hero line adds in.
func (c *Catalog) EcosystemTOML() []byte {
	var b strings.Builder
	b.WriteString(generated + "\n")
	b.WriteString("gems = [\n")
	for _, g := range c.Gems {
		fmt.Fprintf(&b, "  %s,\n", quoteTOML(g.Name))
	}
	b.WriteString("]\n\n")
	b.WriteString("reserved = [\n")
	for _, r := range c.Reserved {
		fmt.Fprintf(&b, "  %s,\n", quoteTOML(r.Org))
	}
	b.WriteString("]\n\n")
	fmt.Fprintf(&b, "# Public repositories holding code across the %d gem organisations.\n", len(c.Gems))
	fmt.Fprintf(&b, "gem_repos = %d\n", c.GemRepos())
	return []byte(b.String())
}

func siteCell(o ResolvedOrg) string {
	if !o.Site {
		return "—"
	}
	return fmt.Sprintf("[site](https://%s.github.io/)", o.Name)
}

func docsCell(o ResolvedOrg) string {
	if !o.Docs {
		return "—"
	}
	return fmt.Sprintf("[docs](https://%s.github.io/docs/)", o.Name)
}

// Page renders f as a documentation page.
//
// It hangs off the resolved family rather than taking a key off the catalogue,
// so that a caller iterating c.Families has no error to handle: a lookup that
// cannot fail is better than one whose failure branch no test can reach.
func (f ResolvedFamily) Page() []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", f.Title, f.Blurb)
	b.WriteString("| Organisation | Repos | Site | Docs | What it holds |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, o := range f.Orgs {
		fmt.Fprintf(&b, "| [`%s`](https://github.com/%s) | %d | %s | %s | %s |\n",
			o.Name, o.Name, o.Repos, siteCell(o), docsCell(o), o.Role)
	}
	b.WriteString("\nCounts are public repositories that hold code; brand, docs and landing\n")
	b.WriteString("repositories are excluded.\n")
	return []byte(b.String())
}

// GemsPage renders the whole gems page: the curated introduction followed by
// the alphabetical table.
func (c *Catalog) GemsPage() []byte {
	var b strings.Builder
	b.WriteString("# Ruby gems — one organisation each\n\n")
	b.WriteString(strings.TrimSpace(c.GemsIntro))
	b.WriteString("\n\n")
	b.WriteString("| Gem | Organisation |\n| --- | --- |\n")
	for _, g := range c.Gems {
		fmt.Fprintf(&b, "| `%s` | [`%s`](https://github.com/%s) |\n", g.Name, g.Org, g.Org)
	}
	fmt.Fprintf(&b, "\n%d gem organisations, %d public code repositories.\n",
		len(c.Gems), c.GemRepos())
	return []byte(b.String())
}

// Summary is the one line every surface repeats, kept in one place so the
// landing page, the profile README and the documentation cannot drift apart.
func (c *Catalog) Summary() string {
	return strconv.Itoa(c.TotalOrgs) + " organisations, " +
		strconv.Itoa(c.TotalRepos) + " public code repositories"
}

// expand substitutes the counted facts into a prose section, so that a sentence
// naming the size of the ecosystem cannot go stale.
func (c *Catalog) expand(s string) string {
	r := strings.NewReplacer(
		"{{summary}}", c.Summary(),
		"{{orgs}}", strconv.Itoa(c.TotalOrgs),
		"{{repos}}", strconv.Itoa(c.TotalRepos),
	)
	return r.Replace(strings.TrimSpace(s))
}

// ProfileREADME renders the organisation profile.
//
// It is generated rather than hand-written for one reason: it is the surface
// most people read, and it repeats every number the landing page carries. Two
// hand-maintained copies of the same count are two counts, and the one nobody
// regenerates is the one that is wrong.
func (c *Catalog) ProfileREADME() []byte {
	var b strings.Builder
	b.WriteString(c.expand(c.ReadmeIntro))
	b.WriteString("\n\n## What every repository is held to\n\n")
	b.WriteString(c.expand(c.ReadmeStandard))
	b.WriteString("\n\n")

	for _, f := range c.Families {
		fmt.Fprintf(&b, "## %s\n\n%s\n\n", f.Title, f.Blurb)
		b.WriteString("| Organisation | Repos | What it holds |\n| --- | --- | --- |\n")
		for _, o := range f.Orgs {
			fmt.Fprintf(&b, "| [`%s`](https://github.com/%s) | %d | %s |\n",
				o.Name, o.Name, o.Repos, o.Role)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Ruby gems — one organisation each\n\n")
	b.WriteString(c.expand(c.GemsIntro))
	fmt.Fprintf(&b, "\n\n<details><summary><strong>%d gem organisations</strong> — click to expand</summary>\n\n",
		len(c.Gems))
	chips := make([]string, 0, len(c.Gems))
	for _, g := range c.Gems {
		chips = append(chips, fmt.Sprintf("[`%s`](https://github.com/%s)", g.Name, g.Org))
	}
	b.WriteString(strings.Join(chips, " · "))
	b.WriteString("\n\n</details>\n\n")

	b.WriteString("## Held, not yet built\n\n")
	b.WriteString(c.expand(c.ReservedIntro))
	b.WriteString("\n\n| Organisation | Intended for |\n| --- | --- |\n")
	for _, r := range c.Reserved {
		fmt.Fprintf(&b, "| [`%s`](https://github.com/%s) | %s |\n", r.Org, r.Org, r.For)
	}

	b.WriteString("\n## Not in this map\n\n| Organisation | What it is |\n| --- | --- |\n")
	for _, n := range c.NotGo {
		fmt.Fprintf(&b, "| [`%s`](https://github.com/%s) | %s |\n", n.Org, n.Org, n.What)
	}

	b.WriteString("\n---\n\n")
	b.WriteString(c.expand(c.ReadmeOutro))
	b.WriteString("\n")
	return []byte(b.String())
}

// ReservedPage renders the documentation page for the reserved names and the
// siblings outside the map.
func (c *Catalog) ReservedPage() []byte {
	var b strings.Builder
	b.WriteString("# Held, not yet built\n\n")
	b.WriteString(c.expand(c.ReservedIntro))
	b.WriteString("\n\n| Organisation | Intended for |\n| --- | --- |\n")
	for _, r := range c.Reserved {
		fmt.Fprintf(&b, "| [`%s`](https://github.com/%s) | %s |\n", r.Org, r.Org, r.For)
	}
	b.WriteString("\n## Not in this map\n\n")
	b.WriteString("These are real and maintained; they are simply not part of the Go library\n")
	b.WriteString("ecosystem this site maps, and are counted nowhere on it.\n\n")
	b.WriteString("| Organisation | What it is |\n| --- | --- |\n")
	for _, n := range c.NotGo {
		fmt.Fprintf(&b, "| [`%s`](https://github.com/%s) | %s |\n", n.Org, n.Org, n.What)
	}
	return []byte(b.String())
}
